In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [11]:
#data type
a.dtype

dtype('int64')

In [12]:
#inducing data type 
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [13]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [14]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [15]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [16]:
#array of zeros, 'd' denotes float64
np.zeros((3,3),'d')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
np.empty((3,3),'d')

array([[ -2.68156159e+154,  -2.32035202e+077,   2.47032823e-323],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [ -2.68156159e+154,  -1.29073865e-231,  -2.68156159e+154]])

In [19]:
#choosing no. of elements between two extremas using LINSPACE
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [20]:
#choosing steps between two extremas
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
#creating random array given shape
np.random.standard_normal((3,4))

array([[ 1.85931694, -1.4620959 ,  0.72038574,  1.20280989],
       [-0.13108747,  1.69193128, -0.41296972,  0.66665398],
       [-0.85295828, -0.56775428, -1.12729287, -0.45661219]])

In [25]:
#stacking up two arrays
a1 = np.random.standard_normal((3,4))
a2 = np.random.standard_normal((3,4))
#this is vertical stack
np.vstack([a1,a2])

array([[-0.88106108,  0.09670183, -0.00411921, -0.98130115],
       [ 0.50520296, -1.39348767, -1.14145097, -1.36340161],
       [-0.84731167, -0.46938785, -1.25903839, -2.25188958],
       [ 1.84409708,  2.74137787, -0.03425122, -1.32571909],
       [-1.72335724,  0.80154126, -0.3769318 ,  0.34774874],
       [-0.28899714,  0.23289447, -0.29265996,  1.63443957]])

In [26]:
#this is horizontal stack
np.hstack([a1,a2])

array([[-0.88106108,  0.09670183, -0.00411921, -0.98130115,  1.84409708,
         2.74137787, -0.03425122, -1.32571909],
       [ 0.50520296, -1.39348767, -1.14145097, -1.36340161, -1.72335724,
         0.80154126, -0.3769318 ,  0.34774874],
       [-0.84731167, -0.46938785, -1.25903839, -2.25188958, -0.28899714,
         0.23289447, -0.29265996,  1.63443957]])

In [27]:
#transpose
a1.transpose()

array([[-0.88106108,  0.50520296, -0.84731167],
       [ 0.09670183, -1.39348767, -0.46938785],
       [-0.00411921, -1.14145097, -1.25903839],
       [-0.98130115, -1.36340161, -2.25188958]])

In [29]:
#saving an array
np.save('random.npy',a1)

In [32]:
#loading the data
a1s = np.load('random.npy')

In [33]:
a1s

array([[-0.88106108,  0.09670183, -0.00411921, -0.98130115],
       [ 0.50520296, -1.39348767, -1.14145097, -1.36340161],
       [-0.84731167, -0.46938785, -1.25903839, -2.25188958]])